language: perl
os:
  - linux
  - osx
node_js:
  - "6"
perl:
  - "5.18"
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
before_install:
    - nvm install 6
    - perl --version
    - node --version
install:
    - npm install
script:
    - npm test