language: perl
os:
  - linux
  - osx
node_js:
  - "6"
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
before_install:
    - nvm install 6
    - perl --version
    - node --version
    # - export PERL5OPT="-I${HOME}/perl5/lib/perl5"
    - echo $PERL5OPT
    - echo $TRAVIS_OS_NAME
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cpanm PadWalker; fi
    - cpanm PadWalker
install:
    - npm install
script:
    - npm run tslint
    - npm test
