# Test against this version of Node.js
environment:
  nodejs_version: "0.10"
  matrix:
  - perl_distribution: "strawberryperl"
  - perl_distribution: "activeperl"

# Install scripts. (runs after repo cloning)
install:
  - cinst $env:perl_distribution
  # - cinst strawberryperl
  # - cinst activeperl
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - perl --version
  # run tests
  - npm test

# Don't actually build.
build: off
